import strawberry
from typing import List, Optional, Any, Dict
from strawberry.types import Info
from loguru import logger

from routes import (
    get_intent_logic,
    get_insight_logic,
    get_topic_logic,
    get_recommendation_logic
)


# 1. DEFINE GRAPHQL DATA TYPES

# A flexible scalar type for raw query rows (dictionary-like structures)
DataRow = strawberry.scalar(
    Any,
    name="DataRow",
    description="A flexible dictionary type representing a single row of raw query data."
)


@strawberry.type
class Chart:
    """Represents a Plotly chart generated as part of an insight."""
    chart: Optional[str] = strawberry.field(description="The Plotly chart represented as a JSON string.")
    chart_type: Optional[str] = strawberry.field(description="The type of chart produced (e.g., 'trend').")
    chart_library: Optional[str] = strawberry.field(description="The charting library used to generate the chart (e.g., 'plotly').")


@strawberry.type
class InsightResponse:
    """Full response returned for an insight query, which may include text, charts, and raw data."""
    output: Optional[str] = strawberry.field(description="The natural language insight generated by the LLM.")
    chart: Optional[Chart] = strawberry.field(description="Chart details if visualization was generated.")
    data_columns: Optional[List[str]] = strawberry.field(description="The list of column names in the raw data table.")
    data_rows: Optional[List[DataRow]] = strawberry.field(description="The raw query result rows.")  # type: ignore


@strawberry.type
class TopicResponse:
    """Response object for topic generation requests."""
    output: str = strawberry.field(description="The generated conversation topic.")


@strawberry.type
class RecommendationResponse:
    """Response object for recommendation generation requests."""
    output: str = strawberry.field(description="The generated recommendation or follow-up question.")


@strawberry.type
class Intent:
    """Represents the detected user intent regarding desired output components."""
    wants_text: bool
    wants_chart: bool
    wants_table: bool
    wants_simplified_numbers: bool


@strawberry.input
class IntentInput:
    """GraphQL input type for passing recognized intent."""
    wants_text: bool
    wants_chart: bool
    wants_table: bool
    wants_simplified_numbers: bool


# 2. DEFINE THE MAIN QUERY & RESOLVERS

@strawberry.type
class Query:

    @strawberry.field
    async def get_insight(self, info: Info, query: str, chat_history: Optional[str] = None, intent: Optional[IntentInput] = None) -> InsightResponse:
        """
        Resolver for generating insights.
        
        Workflow:
        1. Detect which fields are being requested by the client.
        2. Call the core agentic logic with this context.
        3. Return a structured InsightResponse containing text, chart, and/or raw data.
        """
        logger.info(f"GraphQL get_insight called with query: '{query}'")

        if not intent:
            logger.warning("Intent not provided by client, recognizing fallback intent...")
            intent_dict = await get_intent_logic(query)
        else:
            intent_dict = {
                "wants_text": intent.wants_text,
                "wants_chart": intent.wants_chart,
                "wants_table": intent.wants_table,
                "wants_simplified_numbers": intent.wants_simplified_numbers,
            }
        
        logger.info(f"Recognized intent: {intent_dict}")
        
        # 1. Inspect requested fields (text, chart, data table, etc.)
        requested_fields = {field.name for field in info.selected_fields[0].selections}
        logger.info(f"Requested fields: {requested_fields}")

        # 2. Run the main agentic logic
        result_dict = await get_insight_logic(
            query=query,
            chat_history=chat_history,
            requested_fields=list(requested_fields),
            intent=intent_dict  
        )

        # 3. Wrap chart data if it exists
        chart_obj: Optional[Chart] = None
        if result_dict.get("chart"):
            chart_obj = Chart(
                chart=result_dict.get("chart"),
                chart_type=result_dict.get("chart_type"),
                chart_library=result_dict.get("chart_library")
            )
        
        # Return final GraphQL response
        return InsightResponse(
            output=result_dict.get("output"),
            chart=chart_obj,
            data_columns=result_dict.get("data_columns"),
            data_rows=result_dict.get("data_rows")
        )
    
    @strawberry.field
    async def recognize_intent(self, query: str) -> Intent:
        """Resolver that uses LLM logic to detect the user’s intent for text, chart, table, or simplified numbers."""
        intent_dict = await get_intent_logic(query)
        return Intent(**intent_dict)
    
    @strawberry.field
    async def get_topic(self, chat_history: str) -> TopicResponse:
        """Resolver that generates a conversational topic from chat history."""
        topic_text = await get_topic_logic(chat_history)
        return TopicResponse(output=topic_text)

    @strawberry.field
    async def get_recommendation(self, chat_history: str) -> RecommendationResponse:
        """Resolver that generates a recommendation or follow-up question from chat history."""
        rec_text = await get_recommendation_logic(chat_history)
        return RecommendationResponse(output=rec_text)


# 3. CREATE THE FINAL SCHEMA

schema = strawberry.Schema(query=Query)